// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6rVR4whkNWc9QbIv4JEkCHGkRjnvKQDc',
    appId: '1:562939117743:web:6cee7656ad7fc18273545a',
    messagingSenderId: '562939117743',
    projectId: 'my-portfolio-41b68',
    authDomain: 'my-portfolio-41b68.firebaseapp.com',
    storageBucket: 'my-portfolio-41b68.firebasestorage.app',
    measurementId: 'G-E65RCBV3VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC45WjfRsqw7o4kpq2FZ0IyUgqm5WaRu6o',
    appId: '1:562939117743:android:4c5ce8b1c20a410e73545a',
    messagingSenderId: '562939117743',
    projectId: 'my-portfolio-41b68',
    storageBucket: 'my-portfolio-41b68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNjCN4NSkwnpo6cVgeLt2_G7AGH-vl0Q',
    appId: '1:562939117743:ios:38adf69f8d3d9e2b73545a',
    messagingSenderId: '562939117743',
    projectId: 'my-portfolio-41b68',
    storageBucket: 'my-portfolio-41b68.firebasestorage.app',
    iosBundleId: 'com.example.flutterProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADNjCN4NSkwnpo6cVgeLt2_G7AGH-vl0Q',
    appId: '1:562939117743:ios:38adf69f8d3d9e2b73545a',
    messagingSenderId: '562939117743',
    projectId: 'my-portfolio-41b68',
    storageBucket: 'my-portfolio-41b68.firebasestorage.app',
    iosBundleId: 'com.example.flutterProfile',
  );
}
